spring.application.name=bookshelf

server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankcards}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bankcards}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bankcards}
spring.datasource.driver-class-name=org.postgresql.Driver
